import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    dashboard: 'Dashboard',
    staff: 'Staff',
    brands: 'Brands',
    products: 'Products',
    bills: 'Bills',
    customers: 'Customers',
    checkin: 'Check In',
    reports: 'Reports',
    logout: 'Logout',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    close: 'Close',
    confirm: 'Confirm',
    search: 'Search',
    filter: 'Filter',
    refresh: 'Refresh',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Information',
    name: 'Name',
    phone: 'Phone',
    address: 'Address',
    email: 'Email',
    password: 'Password',
    description: 'Description',
    checkInNow: 'Check In Now',
    selectCustomer: 'Select Customer',
    selectCustomerToCheckin: 'Select a customer and take a photo to check in',
    takeShopPhoto: 'Take Shop Photo',
    openCamera: 'Open Camera',
    capturePhoto: 'Capture Photo',
    retake: 'Retake',
    photoReady: 'Photo Ready',
    creating: 'Creating...',
    checkinSuccessful: 'Check-in successful!',
    failedToCheckin: 'Failed to create check-in',
    pleaseFillAllFields: 'Please fill all required fields',
    cameraAccessDenied: 'Camera access denied. Please allow camera permissions.',
    recentCheckins: 'Recent Check-ins',
    checkinsFound: 'check-ins found',
    noRecentCheckins: 'No Recent Check-ins',
    startByCreatingFirstCheckin: 'Start by creating your first check-in above',
    errorLoadingCheckins: 'Error loading check-ins',
    tryRefreshingPage: 'Please try refreshing the page',
    completed: 'Completed',
    customer: 'Customer',
    checkinBy: 'Check-in by',
    viewPhoto: 'View Photo',
    currentUser: 'Current User',
    minutesAgo: 'min ago',
    hoursAgo: 'hrs ago',
    daysAgo: 'days ago',
    currentTime: 'Current Time',
    time: 'Time',
    date: 'Date',
    totalCheckins: 'Total Check-ins',
    todayCheckins: 'Today\'s Check-ins',
    thisWeekCheckins: 'This Week\'s Check-ins',
    trackYourVisits: 'Track your customer visits and manage check-ins',
    deleteCheckin: 'Delete Check-in',
    deleteCheckinConfirmation: 'Are you sure you want to delete this check-in? This action cannot be undone.',
    shop: 'Shop',
    deleting: 'Deleting...',
    checkinDeletedSuccessfully: 'Check-in deleted successfully',
    failedToDeleteCheckin: 'Failed to delete check-in',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    download: 'Download',
    checkinPhoto: 'Check-in Photo',
    failedToLoadImage: 'Failed to load image',
    stockReport: 'Stock Report',
    customerBalanceReport: 'Customer Balance Report',
    salesReport: 'Sales Report',
    paymentsReport: 'Payments Report',
    reportCenter: 'Report Center',
    generateDetailedReports: 'Generate and download detailed reports',
    productName: 'Product Name',
    remainingStock: 'Remaining Stock',
    unit: 'Unit',
    price: 'Price',
    brand: 'Brand',
    stockValue: 'Stock Value',
    shopName: 'Shop Name',
    ownerName: 'Owner Name',
    balance: 'Balance',
    paidAmount: 'Paid Amount',
    pendingAmount: 'Pending Amount',
    billDate: 'Bill Date',
    billNumber: 'Bill Number',
    totalAmount: 'Total Amount',
    createdBy: 'Created By',
    paymentDate: 'Payment Date',
    amount: 'Amount',
    paymentMode: 'Payment Mode',
    referenceNumber: 'Reference Number',
    receivedBy: 'Received By',
    summary: 'Summary',
    totalSales: 'Total Sales',
    totalPaid: 'Total Paid',
    totalPending: 'Total Pending',
    totalPayments: 'Total Payments',
    count: 'Count',
    fromDate: 'From Date',
    toDate: 'To Date',
    noDataFound: 'No data found',
    failedToLoadReport: 'Failed to load report',
    clickToViewDetails: 'Click to view details',
    totalStaff: 'Total Staff',
    totalProducts: 'Total Products',
    totalCustomers: 'Total Customers',
    todayBills: 'Today\'s Bills',
    overview: 'Overview',
    recentActivity: 'Recent Activity',
    addProduct: 'Add Product',
    addCustomer: 'Add Customer',
    // New dashboard translations
    todaySales: 'Today\'s Sales',
    monthlySales: 'Monthly Sales',
    yearlySales: 'Yearly Sales',
    todayProfit: 'Today\'s Profit',
    monthlyProfit: 'Monthly Profit',
    yearlyProfit: 'Yearly Profit',
    pendingCustomers: 'Pending Customers',
    pendingBills: 'Pending Bills',
    lowStockItems: 'Low Stock Items',
    outOfStockItems: 'Out of Stock Items',
    inventoryValue: 'Inventory Value',
    recentBills: 'Recent Bills',
    recentPayments: 'Recent Payments',
    topProducts: 'Top Products',
    topCustomers: 'Top Customers',
    paid: 'Paid',
    pending: 'Pending',
    cash: 'Cash',
    upi: 'UPI',
    card: 'Card',
    bank: 'Bank Transfer',
    totalSold: 'Total Sold',
    totalPurchases: 'Total Purchases',
    withPending: 'With Pending',
    salesOverview: 'Sales Overview',
    profitOverview: 'Profit Overview',
    quickStats: 'Quick Stats',
    failedToLoadDashboard: 'Failed to load dashboard data',
    // Bills page translations
    manageBillsAndPayments: 'Manage bills and track payments',
    recordPayment: 'Record Payment',
    createBill: 'Create Bill',
    totalBills: 'Total Bills',
    billHistory: 'Bill History',
    billsFound: 'bills found',
    errorLoadingBills: 'Error loading bills',
    noBillsFound: 'No Bills Found',
    tryAdjustingSearchCriteria: 'Try adjusting your search criteria',
    createNewBill: 'Create New Bill',
    billCreationDescription: 'Fill in the details below to create a new bill',
    paidLabel: 'Paid',
    pendingLabel: 'Pending',
    fullyPaid: 'Fully Paid',
    // Customer page translations
    manageCustomerRelationships: 'Manage customer relationships and purchase history',
    customersFound: 'customers found',
    noCustomersFound: 'No customers found',
    customerList: 'Customer List',
    totalBalance: 'Total Balance',
    editCustomer: 'Edit Customer',
    addCustomerDescription: 'Fill in the customer details below',
    editCustomerDescription: 'Update the customer information',
    enterShopName: 'Enter shop name',
    enterOwnerName: 'Enter owner name',
    enterPhoneNumber: 'Enter phone number',
    enterAddress: 'Enter address',
    customerCreatedSuccessfully: 'Customer created successfully',
    customerUpdatedSuccessfully: 'Customer updated successfully',
    failedToCreateCustomer: 'Failed to create customer',
    failedToUpdateCustomer: 'Failed to update customer',
    update: 'Update',
    create: 'Create',
    // Product page translations
    manageProductInventory: 'Manage your product inventory and stock levels',
    productList: 'Product List',
    productsFound: 'products found',
    noProductsFound: 'No products found',
    tryAdjustingSearch: 'Try adjusting your search criteria',
    editProduct: 'Edit Product',
    selectBrand: 'Select Brand',
    quantity: 'Quantity',
    initialStock: 'Initial Stock',
    unitPlaceholder: 'kg, pieces, etc.',
    // Stock status translations
    outOfStock: 'Out of Stock',
    lowStock: 'Low Stock',
    inStock: 'In Stock',
    remaining: 'remaining',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    staff: 'ஊழியர்கள்',
    brands: 'பிராண்டுகள்',
    products: 'தயாரிப்புகள்',
    bills: 'கணக்குகள்',
    customers: 'வாடிக்கையாளர்கள்',
    checkin: 'செக் இன்',
    reports: 'அறிக்கைகள்',
    logout: 'வெளியேறு',
    add: 'சேர்க்க',
    edit: 'திருத்து',
    delete: 'நீக்கு',
    save: 'சேமி',
    cancel: 'ரத்து',
    submit: 'சமர்ப்பிக்க',
    close: 'மூடு',
    confirm: 'உறுதிப்படுத்து',
    search: 'தேடு',
    filter: 'வடிகட்டு',
    refresh: 'புதுப்பி',
    loading: 'ஏற்றுகிறது...',
    error: 'பிழை',
    success: 'வெற்றி',
    warning: 'எச்சரிக்கை',
    info: 'தகவல்',
    name: 'பெயர்',
    phone: 'தொலைபேசி',
    address: 'முகவரி',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    description: 'விளக்கம்',
    checkInNow: 'இப்போது செக் இன் செய்யுங்கள்',
    selectCustomer: 'வாடிக்கையாளரைத் தேர்ந்தெடுக்கவும்',
    selectCustomerToCheckin: 'வாடிக்கையாளரைத் தேர்ந்தெடுத்து செக் இன் செய்ய புகைப்படம் எடுக்கவும்',
    takeShopPhoto: 'கடை புகைப்படம் எடுக்கவும்',
    openCamera: 'கேமராவைத் திறக்கவும்',
    capturePhoto: 'புகைப்படம் எடுக்கவும்',
    retake: 'மீண்டும் எடுக்கவும்',
    photoReady: 'புகைப்படம் தயார்',
    creating: 'உருவாக்குகிறது...',
    checkinSuccessful: 'செக்-இன் வெற்றிகரமாக முடிந்தது!',
    failedToCheckin: 'செக்-இன் உருவாக்க முடியவில்லை',
    pleaseFillAllFields: 'தயவுசெய்து அனைத்து தேவையான புலங்களையும் நிரப்பவும்',
    cameraAccessDenied: 'கேமரா அணுகல் மறுக்கப்பட்டது. தயவுசெய்து கேமரா அனுமதிகளை அனுமதிக்கவும்.',
    recentCheckins: 'சமீபத்திய செக்-இன்கள்',
    checkinsFound: 'செக்-இன்கள் கண்டறியப்பட்டன',
    noRecentCheckins: 'சமீபத்திய செக்-இன்கள் இல்லை',
    startByCreatingFirstCheckin: 'மேலே உங்கள் முதல் செக்-இனை உருவாக்குவதன் மூலம் தொடங்கவும்',
    errorLoadingCheckins: 'செக்-இன்களை ஏற்றுவதில் பிழை',
    tryRefreshingPage: 'தயவுசெய்து பக்கத்தைப் புதுப்பிக்க முயற்சிக்கவும்',
    completed: 'முடிந்தது',
    customer: 'வாடிக்கையாளர்',
    checkinBy: 'செக்-இன் செய்தவர்',
    viewPhoto: 'புகைப்படத்தைப் பார்க்கவும்',
    currentUser: 'தற்போதைய பயனர்',
    minutesAgo: 'நிமிடங்களுக்கு முன்பு',
    hoursAgo: 'மணிநேரங்களுக்கு முன்பு',
    daysAgo: 'நாட்களுக்கு முன்பு',
    currentTime: 'தற்போதைய நேரம்',
    time: 'நேரம்',
    date: 'தேதி',
    totalCheckins: 'மொத்த செக்-இன்கள்',
    todayCheckins: 'இன்றைய செக்-இன்கள்',
    thisWeekCheckins: 'இந்த வாரத்தின் செக்-இன்கள்',
    trackYourVisits: 'உங்கள் வாடிக்கையாளர் வருகைகளைக் கண்காணித்து செக்-இன்களை நிர்வகிக்கவும்',
    deleteCheckin: 'செக்-இனை நீக்கவும்',
    deleteCheckinConfirmation: 'இந்த செக்-இனை நீக்க விரும்புகிறீர்களா? இந்த செயலை மாற்ற முடியாது.',
    shop: 'கடை',
    deleting: 'நீக்குகிறது...',
    checkinDeletedSuccessfully: 'செக்-இன் வெற்றிகரமாக நீக்கப்பட்டது',
    failedToDeleteCheckin: 'செக்-இனை நீக்க முடியவில்லை',
    zoomIn: 'பெரிதாக்கு',
    zoomOut: 'சிறிதாக்கு',
    download: 'பதிவிறக்கு',
    checkinPhoto: 'செக்-இன் புகைப்படம்',
    failedToLoadImage: 'படத்தை ஏற்ற முடியவில்லை',
    stockReport: 'பங்கு அறிக்கை',
    customerBalanceReport: 'வாடிக்கையாளர் இருப்பு அறிக்கை',
    salesReport: 'விற்பனை அறிக்கை',
    paymentsReport: 'கட்டணங்கள் அறிக்கை',
    reportCenter: 'அறிக்கை மையம்',
    generateDetailedReports: 'விரிவான அறிக்கைகளை உருவாக்கி பதிவிறக்கம் செய்யுங்கள்',
    productName: 'தயாரிப்பு பெயர்',
    remainingStock: 'மீதமுள்ள பங்கு',
    unit: 'அலகு',
    price: 'விலை',
    brand: 'பிராண்ட்',
    stockValue: 'பங்கு மதிப்பு',
    shopName: 'கடை பெயர்',
    ownerName: 'உரிமையாளர் பெயர்',
    balance: 'இருப்பு',
    paidAmount: 'செலுத்திய தொகை',
    pendingAmount: 'நிலுவைத் தொகை',
    billDate: 'பில் தேதி',
    billNumber: 'பில் எண்',
    totalAmount: 'மொத்த தொகை',
    createdBy: 'உருவாக்கியவர்',
    paymentDate: 'பணம் செலுத்திய தேதி',
    amount: 'தொகை',
    paymentMode: 'பணம் செலுத்தும் முறை',
    referenceNumber: 'குறிப்பு எண்',
    receivedBy: 'பெற்றவர்',
    summary: 'சுருக்கம்',
    totalSales: 'மொத்த விற்பனை',
    totalPaid: 'மொத்த செலுத்தப்பட்டது',
    totalPending: 'மொத்த நிலுவை',
    totalPayments: 'மொத்த கட்டணங்கள்',
    count: 'எண்ணிக்கை',
    fromDate: 'தொடக்க தேதி',
    toDate: 'முடிவு தேதி',
    noDataFound: 'தரவு கிடைக்கவில்லை',
    failedToLoadReport: 'அறிக்கையை ஏற்ற முடியவில்லை',
    clickToViewDetails: 'விவரங்களைப் பார்க்க கிளிக் செய்யவும்',
    totalStaff: 'மொத்த ஊழியர்கள்',
    totalProducts: 'மொத்த தயாரிப்புகள்',
    totalCustomers: 'மொத்த வாடிக்கையாளர்கள்',
    todayBills: 'இன்றைய பில்கள்',
    overview: 'மேலோட்டம்',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    addProduct: 'தயாரிப்பு சேர்',
    addCustomer: 'வாடிக்கையாளர் சேர்',
    // New dashboard translations in Tamil
    todaySales: 'இன்றைய விற்பனை',
    monthlySales: 'மாதாந்திர விற்பனை',
    yearlySales: 'வருடாந்திர விற்பனை',
    todayProfit: 'இன்றைய லாபம்',
    monthlyProfit: 'மாதாந்திர லாபம்',
    yearlyProfit: 'வருடாந்திர லாபம்',
    pendingCustomers: 'நிலுவையில் உள்ள வாடிக்கையாளர்கள்',
    pendingBills: 'நிலுவையில் உள்ள பில்கள்',
    lowStockItems: 'குறைந்த பங்கு பொருட்கள்',
    outOfStockItems: 'இல்லாத பொருட்கள்',
    inventoryValue: 'சரக்கு மதிப்பு',
    recentBills: 'சமீபத்திய பில்கள்',
    recentPayments: 'சமீபத்திய கட்டணங்கள்',
    topProducts: 'சிறந்த தயாரிப்புகள்',
    topCustomers: 'சிறந்த வாடிக்கையாளர்கள்',
    paid: 'செலுத்தப்பட்டது',
    pending: 'நிலுவை',
    cash: 'பணம்',
    upi: 'யூபிஐ',
    card: 'கார்டு',
    bank: 'வங்கி பரிமாற்றம்',
    totalSold: 'மொத்த விற்பனை',
    totalPurchases: 'மொத்த வாங்குதல்கள்',
    withPending: 'நிலுவையுடன்',
    salesOverview: 'விற்பனை மேலோட்டம்',
    profitOverview: 'லாப மேலோட்டம்',
    quickStats: 'விரைவு புள்ளிவிவரங்கள்',
    failedToLoadDashboard: 'டாஷ்போர்ட் தரவை ஏற்ற முடியவில்லை',
    // Bills page translations in Tamil
    manageBillsAndPayments: 'பில்களை நிர்வகித்து கட்டணங்களைக் கண்காணிக்கவும்',
    recordPayment: 'கட்டணம் பதிவு செய்யுங்கள்',
    createBill: 'பில் உருவாக்கவும்',
    totalBills: 'மொத்த பில்கள்',
    billHistory: 'பில் வரலாறு',
    billsFound: 'பில்கள் கண்டறியப்பட்டன',
    errorLoadingBills: 'பில்களை ஏற்றுவதில் பிழை',
    noBillsFound: 'பில்கள் எதுவும் இல்லை',
    tryAdjustingSearchCriteria: 'உங்கள் தேடல் அளவீடுகளை சரிசெய்ய முயற்சிக்கவும்',
    createNewBill: 'புதிய பில் உருவாக்கவும்',
    billCreationDescription: 'புதிய பில் உருவாக்க கீழே உள்ள விவரங்களை நிரப்பவும்',
    paidLabel: 'செலுத்தப்பட்டது',
    pendingLabel: 'நிலுவை',
    fullyPaid: 'முழுமையாக செலுத்தப்பட்டது',
    // Customer page translations in Tamil
    manageCustomerRelationships: 'வாடிக்கையாளர் உறவுகளை நிர்வகித்து வாங்குதல் வரலாறைக் கண்காணிக்கவும்',
    customersFound: 'வாடிக்கையாளர்கள் கண்டறியப்பட்டன',
    noCustomersFound: 'வாடிக்கையாளர்கள் எவரும் இல்லை',
    customerList: 'வாடிக்கையாளர் பட்டியல்',
    totalBalance: 'மொத்த இருப்பு',
    editCustomer: 'வாடிக்கையாளரைத் திருத்து',
    addCustomerDescription: 'கீழே வாடிக்கையாளர் விவரங்களை நிரப்பவும்',
    editCustomerDescription: 'வாடிக்கையாளர் தகவலைப் புதுப்பிக்கவும்',
    enterShopName: 'கடை பெயரை உள்ளிடவும்',
    enterOwnerName: 'உரிமையாளர் பெயரை உள்ளிடவும்',
    enterPhoneNumber: 'தொலைபேசி எண்ணை உள்ளிடவும்',
    enterAddress: 'முகவரியை உள்ளிடவும்',
    customerCreatedSuccessfully: 'வாடிக்கையாளர் வெற்றிகரமாக உருவாக்கப்பட்டார்',
    customerUpdatedSuccessfully: 'வாடிக்கையாளர் வெற்றிகரமாக புதுப்பிக்கப்பட்டார்',
    failedToCreateCustomer: 'வாடிக்கையாளரை உருவாக்க முடியவில்லை',
    failedToUpdateCustomer: 'வாடிக்கையாளரைப் புதுப்பிக்க முடியவில்லை',
    update: 'புதுப்பி',
    create: 'உருவாக்கு',
    // Product page translations in Tamil
    manageProductInventory: 'உங்கள் தயாரிப்பு சரக்கு மற்றும் பங்கு நிலைகளை நிர்வகிக்கவும்',
    productList: 'தயாரிப்பு பட்டியல்',
    productsFound: 'தயாரிப்புகள் கண்டறியப்பட்டன',
    noProductsFound: 'தயாரிப்புகள் எதுவும் இல்லை',
    tryAdjustingSearch: 'உங்கள் தேடல் அளவீடுகளைச் சரிசெய்ய முயற்சிக்கவும்',
    editProduct: 'தயாரிப்பைத் திருத்து',
    selectBrand: 'பிராண்டைத் தேர்ந்தெடுக்கவும்',
    quantity: 'அளவு',
    initialStock: 'ஆரம்ப பங்கு',
    unitPlaceholder: 'கிலோகிராம், துண்டுகள், போன்றவை',
    // Stock status translations in Tamil
    outOfStock: 'பங்கு இல்லை',
    lowStock: 'குறைந்த பங்கு',
    inStock: 'பங்கில் உள்ளது',
    remaining: 'மீதமுள்ளது',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<string>('en');

  const t = (key: string): string => {
    return translations[language as keyof typeof translations]?.[key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
